
spring:
  config:
    on-not-found: ignore
    import: classpath:aws.yml
  datasource:
    url: jdbc:postgresql://fitqa-db-dev.czkattcbnkfu.ap-northeast-2.rds.amazonaws.com:5432/fitqa-db-dev
    username: fitqadmin
    password: vltzk123!
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    include:
      - oauth
      - aws

server:
  port: 8080
