###
# 모든 Trainer 들을 가져옵니다
# TrainerApiController::getTrainersAll
GET http://localhost:8080/api/v1/trainers
Accept: application/json

###
# 특정 Trainer의 정보를 가져옵니다
# TrainerApiController::getTrainerById

GET http://localhost:8080/api/v1/trainers/trn_qQYHg782nZ4qKC3i
Accept: application/json

###
# 트레이너와 관련된 피드백 리스트를 가져옵니다
# TrainerApiController::getTrainerFeedbacks

GET http://localhost:8080/api/v1/trainers/trn_YC9zWA8gVBmzo5uQ/feedbacks
Accept: application/json


###
# InterestAreas가 일치하는 Trainer 들을 가져옵니다.
# TrainerApiController::getTrainerByInterestAreas

GET http://localhost:8080/api/v1/trainers?interestAreas="LOWER"&interestAreas="BACK"
Accept: application/json

###
# 트레이너를 등록합니다
# TrainerApiController::registerTrainer

POST http://localhost:8080/api/v1/trainers
Content-Type: application/json

{
  "name": "오상헌",
  "style": "BODY_BUILDING"
}

###
# 트레이너의 관심 부위 정보를 변경합니다
# TrainerApiController::updateTrainerInterestAreas

PUT http://localhost:8080/api/v1/trainers/trn_EfF1W4nfWsOoDx49/interestAreas
Content-Type: application/json

{
  "interestAreas": [
    "LOWER",
    "BACK"
  ]
}

###
# 트레이너의 정보를 변경합니다.
# TrainerApiController::updateTrainerInfo

PUT http://localhost:8080/api/v1/trainers/trn_EfF1W4nfWsOoDx49/
Content-Type: application/json

{
  "name": "오상헌333",
  "style": "BODY_BUILDING",
  "introduceTitle": "소개 제목을 변경합니다777",
  "introduceContext": "소개 내용을 변경합니다777",
  "careers": [
    {
      "description": "1번 경력입니다.",
      "type": "CAREER"
    }
  ],
  "feedbackPrices": [
    {
      "area": "LOWER",
      "price": 6000
    }
  ],
  "interestAreas": [
    {
      "interestArea": "CHEST"
    },
    {
      "interestArea": "SHOULDER"
    }
  ],
  "sns": [
    {
      "snsUrl": "Sns 3 Url",
      "snsType": "INSTAGRAM"
    }
  ]
}