###
# 모든 Trainer 들을 가져옵니다

GET http://localhost:8080/api/v1/trainers
Accept: application/json

###
# InterestAreas가 일치하는 Trainer 들을 가져옵니다.

GET http://localhost:8080/api/v1/trainers?interestAreas="LOWER"&interestAreas="BACK"
###
# 특정 Trainer의 정보를 가져옵니다

GET http://localhost:8080/api/v1/trainers/trn_qQYHg782nZ4qKC3i
Accept: application/json

###
# 트레이너를 등록합니다
POST http://localhost:8080/api/v1/trainers
Content-Type: application/json

{
  "name": "트레이너 이름2",
  "style": "BODY_BUILDING"
}

###
# 트레이너의 정보를 변경합니다

PUT http://localhost:8080/api/v1/trainers/trn_ziLsDrMChNKdUyv3
Content-Type: application/json

{
  "style": "BODY_BUILDING",
  "introduceTitle": "변경된 소개 제목1234",
  "introduceContext": "변경된 소개 내용1234",
  "interestAreas": [
    "LOWER",
    "BACK",
    "CHEST",
    "SHOULDER"
  ]
}